### ISSUE TITLE
Using outerHTML instead of innerHTML

### ISSUE THREAD

**Issue by ivansieder** [simedia-tech/modly-js#5]
Instead of using the innerHTML to use a DOM node as content, the outerHTML should be used, as we want to be able to have the complete HTML inside the Dialog instead of just the innerHTML.

**Comment by rmoswela** [comment]
I will try this one ;-)

**Comment by ivansieder** [comment]
Hi @rmoswela, thanks for your interest! Right now there's already @nightelves working on it, but you are free to choose another issue, that noone has taken yet! :)
