### ISSUE TITLE
Apply flex-start for too big dialogs directly on the element

### ISSUE THREAD

**Issue by ivansieder** [simedia-tech/modly-js#6]
Currently, when a modly dialog content is bigger than the window, only the class "anchored" is being added to it, and that class has the "flex-start" set for vertical positioning. However, this is being overwritten by the element styles. That's why the flex-start for big dialogs should be removed from the class and added directly to the element when the positioning is being calculated.

**Comment by dadams89** [comment]
Looking into this!
